#!/usr/bin/env python3
import soap
from soap import (
    IntegerInterval, FloatInterval, FractionInterval, ErrorSemantics,
    mpz, mpq, mpfr, mpz_type, mpq_type, mpfr_type, inf, ulp, cast,
    BoxState, expr, flow, logger
)


def pr(*args):
    with soap.logger.info_context():
        soap.logger.info(*args)
ps = lambda *args: pr(*[str(a) for a in args])


I = Int = soap.semantics.IntegerInterval
F = Float = soap.semantics.FloatInterval
E = Error = soap.semantics.ErrorSemantics
S = Box = soap.semantics.BoxState


if __name__ == '__main__':
    from soap.shell import Shell, trace
    with logger.info_context():
        Shell()()
