#!/usr/bin/env python3
import soap
from soap import (
    context, IntegerInterval, FloatInterval, FractionInterval, ErrorSemantics,
    mpz, mpq, mpfr, mpz_type, mpq_type, mpfr_type, inf, ulp, cast, BoxState,
    expr, flow, closure, expand, reduce, parsings, martel_trace, greedy_trace,
    frontier_trace, logger
)


def pr(*args):
    with soap.logger.info_context():
        soap.logger.info(*args)
ps = lambda *args: pr(*[str(a) for a in args])


class __IntervalShortcut(object):
    def __init__(self, cls):
        self.cls = cls

    def __getitem__(self, key):
        return self.cls(key)


class __StateShortcut(object):
    def __init__(self, cls):
        self.cls = cls

    def __getitem__(self, key):
        if not isinstance(key, slice):
            raise TypeError(
                'State shortcut accepts keys in the form of variable:value.')
        s = self.cls()
        s[key.start] = key.stop
        return s


I = Int = IntegerInterval
F = Float = FloatInterval
E = Error = ErrorSemantics
S = Box = BoxState
i = __IntervalShortcut(IntegerInterval)
f = __IntervalShortcut(FloatInterval)
e = __IntervalShortcut(ErrorSemantics)
s = __StateShortcut(BoxState)
ctx = context


if __name__ == '__main__':
    from soap.shell import Shell, trace
    with logger.info_context():
        Shell()()
